CREATE DATABASE IF NOT EXISTS exam_portal
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE exam_portal;

CREATE TABLE IF NOT EXISTS app_state (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  state_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS students (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  app_id INT UNSIGNED NULL,
  enroll VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  exam_code VARCHAR(16) NULL,
  section VARCHAR(64) NULL,
  year VARCHAR(32) NULL,
  branch VARCHAR(128) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS faculty (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL,
  code VARCHAR(16) NULL,
  depts_json LONGTEXT NOT NULL,
  subjects_json LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS questions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dept VARCHAR(128) NOT NULL,
  subject VARCHAR(128) NOT NULL,
  q_index INT UNSIGNED NOT NULL,
  question_text TEXT NOT NULL,
  options_json LONGTEXT NOT NULL,
  correct_index TINYINT UNSIGNED NOT NULL,
  chapter VARCHAR(128) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_questions_dept_subject (dept, subject)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO app_state (id, state_json)
VALUES (1, '{}')
ON DUPLICATE KEY UPDATE id = id;
